spring:
  datasource:
    #url: jdbc:mysql://localhost:3306/newdb
    #username: root
    #password: password
    url: jdbc:mysql://144.91.114.64:3306/develhope_tests
    username: exory
    password: Vindictive221297/

    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update

  sql:
    init:
      mode: always